# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb2.field_behavior_pb2 as field__behavior__pb2
import pb2.postal_address_pb2 as postal__address__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raddress.proto\x12 google.maps.addressvalidation.v1\x1a\x14\x66ield_behavior.proto\x1a\x14postal_address.proto\"\x8f\x02\n\x07\x41\x64\x64ress\x12\x19\n\x11\x66ormatted_address\x18\x02 \x01(\t\x12\x32\n\x0epostal_address\x18\x03 \x01(\x0b\x32\x1a.google.type.PostalAddress\x12T\n\x12\x61\x64\x64ress_components\x18\x04 \x03(\x0b\x32\x32.google.maps.addressvalidation.v1.AddressComponentB\x04\xe2\x41\x01\x06\x12\x1f\n\x17missing_component_types\x18\x05 \x03(\t\x12#\n\x1bunconfirmed_component_types\x18\x06 \x03(\t\x12\x19\n\x11unresolved_tokens\x18\x07 \x03(\t\"\xae\x03\n\x10\x41\x64\x64ressComponent\x12G\n\x0e\x63omponent_name\x18\x01 \x01(\x0b\x32/.google.maps.addressvalidation.v1.ComponentName\x12\x16\n\x0e\x63omponent_type\x18\x02 \x01(\t\x12`\n\x12\x63onfirmation_level\x18\x03 \x01(\x0e\x32\x44.google.maps.addressvalidation.v1.AddressComponent.ConfirmationLevel\x12\x10\n\x08inferred\x18\x04 \x01(\x08\x12\x17\n\x0fspell_corrected\x18\x05 \x01(\x08\x12\x10\n\x08replaced\x18\x06 \x01(\x08\x12\x12\n\nunexpected\x18\x07 \x01(\x08\"\x85\x01\n\x11\x43onfirmationLevel\x12\"\n\x1e\x43ONFIRMATION_LEVEL_UNSPECIFIED\x10\x00\x12\r\n\tCONFIRMED\x10\x01\x12\x1d\n\x19UNCONFIRMED_BUT_PLAUSIBLE\x10\x02\x12\x1e\n\x1aUNCONFIRMED_AND_SUSPICIOUS\x10\x03\"4\n\rComponentName\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\tB\x89\x02\n$com.google.maps.addressvalidation.v1B\x0c\x41\x64\x64ressProtoP\x01ZXcloud.google.com/go/maps/addressvalidation/apiv1/addressvalidationpb;addressvalidationpb\xf8\x01\x01\xa2\x02\x07GMPAVV1\xaa\x02 Google.Maps.AddressValidation.V1\xca\x02 Google\\Maps\\AddressValidation\\V1\xea\x02#Google::Maps::AddressValidation::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'address_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.google.maps.addressvalidation.v1B\014AddressProtoP\001ZXcloud.google.com/go/maps/addressvalidation/apiv1/addressvalidationpb;addressvalidationpb\370\001\001\242\002\007GMPAVV1\252\002 Google.Maps.AddressValidation.V1\312\002 Google\\Maps\\AddressValidation\\V1\352\002#Google::Maps::AddressValidation::V1'
  _ADDRESS.fields_by_name['address_components']._options = None
  _ADDRESS.fields_by_name['address_components']._serialized_options = b'\342A\001\006'
  _globals['_ADDRESS']._serialized_start=96
  _globals['_ADDRESS']._serialized_end=367
  _globals['_ADDRESSCOMPONENT']._serialized_start=370
  _globals['_ADDRESSCOMPONENT']._serialized_end=800
  _globals['_ADDRESSCOMPONENT_CONFIRMATIONLEVEL']._serialized_start=667
  _globals['_ADDRESSCOMPONENT_CONFIRMATIONLEVEL']._serialized_end=800
  _globals['_COMPONENTNAME']._serialized_start=802
  _globals['_COMPONENTNAME']._serialized_end=854
# @@protoc_insertion_point(module_scope)
